### ISSUE TITLE
Search Error

### ISSUE THREAD

**Issue by tinkuperera** [AzizKpln/Moriarty-Project#15]
I am getting this error after giving MS account, and mobile number. Please help...

Traceback (most recent call last):
  File "Moriarty.py", line 179, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "Moriarty.py", line 61, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div/main/div/a[2]"))).click()
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by AzizKpln** [comment]
Dont run it as root

**Comment by tinkuperera** [comment]
Thank you so much for the reply. I tried run it as a non root user. But still getting the same error. can you please help me...

**Comment by AzizKpln** [comment]
Are you using kali Linux 2020.4?

**Comment by AzizKpln** [comment]
I tested it. I dont get an error.

**Comment by tinkuperera** [comment]
Brother , I am using  kali Linux 2020.2. so you suggest 2020.4 right ?
