### ISSUE TITLE
try running without root

### ISSUE THREAD

**Issue by Noegs** [AzizKpln/Moriarty-Project#17]
i try to running without root then i hv problem :

Traceback (most recent call last):
  File "Moriarty.py", line 167, in <module>
    with open("output/comments2.txt","w+") as file:
PermissionError: [Errno 13] Permission denied: 'output/comments2.txt'

my OS Kali Linux ver 2020.3

what suppose to do?

**Comment by AzizKpln** [comment]
When you are inside of the Moriarty-Project, issue this command:

chown -R kali:kali *

Kali is the username. If the User is not kali, change the command with the user's name

**Comment by Noegs** [comment]
ok thanks bro...
