### ISSUE TITLE
Owner Of The Number:Invaild Microsoft Account And Password!

### ISSUE THREAD

**Issue by NassemKa** [AzizKpln/Moriarty-Project#18]
Hello, it seems like in v2.6 there is an error in connecting to Microsoft account,
I use this format for the tool : python3 Moriarty.py -m xxxxx@outlook.com -p xxxxxxxxx -n +9xxxxxxxx, without root and it always return this line, Owner Of The Number:Invaild Microsoft Account And Password!\
I have tried multiple Microsoft account and still it didn't work, also why logging in with gmail option has been removed it was working like charm before

**Comment by AzizKpln** [comment]
because google blocks logging after a while. i've tested it and you're right. There  is an error in the owner-finder function. I'll try to fix it soon but im not sure when

**Comment by AzizKpln** [comment]
Tool has been updated. You won't be encountering with errors.
