### ISSUE TITLE
bağlantı kopukluğu

### ISSUE THREAD

**Issue by plt66** [AzizKpln/Moriarty-Project#2]
![yeni](https://user-images.githubusercontent.com/33508073/81472005-4164d980-91c3-11ea-88b4-2645869e332f.png)

**Comment by AzizKpln** [comment]
sırasıyla şu komutları girer misin
linux terminal açık iken;

python3
import selenium
selenium.__version__

**Comment by plt66** [comment]
![tt](https://user-images.githubusercontent.com/33508073/81472693-c7831f00-91c7-11ea-8eb7-341453f9b179.png)
bu şekilde

**Comment by AzizKpln** [comment]
koda bir daha bak kod satırına almadığımdan _'ler görülmemiş

**Comment by plt66** [comment]
3.141.0

**Comment by AzizKpln** [comment]
tamamdır requirements.txt ekliyeceğim araca version'un 4.0.0.a1 olması gerekiyor teşekkürler bildirim için

**Comment by AzizKpln** [comment]
pip3 install -r requirements.txt komutu sorununu çözecektir çözmezse tekrar bildirmekten çekinme lütfen

**Comment by AzizKpln** [comment]
it is solved
