### ISSUE TITLE
03/04/2021 error iv done everything i suppose to do please help urgently thank you ASAP

### ISSUE THREAD

**Issue by Feten1001** [AzizKpln/Moriarty-Project#25]
i need help i dont get it at all what do i do thank you 

iv installed it and everything and then it was downloading for like 10 mins then i type 

**_**cd Moriarty-Project**_**
then
**python3 Moriarty.py -m kalitesting1234@outlook.com -p ************** -n +4474**********

outlook is microsoft also and this comes up 

then it comes like this 

**Owner Name/Number Information:**

**Traceback (most recent call last):**
  **File "/home/birksy/Moriarty-Project/Moriarty.py", line 179, in <module>**
    **microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)**
  **File "/home/birksy/Moriarty-Project/Moriarty.py", line 62, in microsoft_mail**
    **WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH,** **"/html/body/div/form[1]/div/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/input[1]"))).send_keys(username)**
  **File "/home/birksy/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 86, in until**
    **raise TimeoutException(message, screen, stacktrace)**
**selenium.common.exceptions.TimeoutException: Message:**

how to fix this error

**Comment by AzizKpln** [comment]
Hi, you did everything right. The tool does not work properly at the moment. I will work on this project to fix  these kind of errors. It will be working properly again like in a month.

**Comment by AzizKpln** [comment]
Tool has been updated. You won't be encountring with errors.
