### ISSUE TITLE
ModuleNotFoundError: No module named 'clint'

### ISSUE THREAD

**Issue by Qutaibamo** [AzizKpln/Moriarty-Project#37]
I was Running Normally On this Command and 

python3 Moriarty.py -n +phone_number
------------------------------------------
Traceback (most recent call last):
  File "/home/kali/Moriarty-Project/Moriarty.py", line 14, in <module>
    from clint.textui import colored
ModuleNotFoundError: No module named 'clint'

**Comment by rohandeadshot** [comment]
use this command (pip3 install -r requirements.txt)

**Comment by AzizKpln** [comment]
Updated
