### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by shanow7** [AzizKpln/Moriarty-Project#4]
Hi I've problem with start this ripo
![image](https://user-images.githubusercontent.com/37192410/81485774-08bf1180-9250-11ea-85c0-09889cd12578.png)

can you help?

**Comment by AzizKpln** [comment]
did you make the installation? I mean ./install.sh and pip3 install -r requirements.txt?

**Comment by shanow7** [comment]
yesTemat: Re: [AzizKpln/Moriarty-Project] problem (#4)Data: 2020-05-10 0:27Nadawca: "Aziz Kaplan" Adresat: "AzizKpln/Moriarty-Project" ; DW: "shanow7" ; "Author" ; 
did you make the installation? I mean ./install.sh and pip3 install -r requirements.txt?

**Comment by AzizKpln** [comment]
Try to install the tool again I made some changes.

 I installed and I ran the tool successfully in kali2020.1 it shouldnt give an error.

**Comment by shanow7** [comment]
I try to use install to:python&nbsp; 3.7.7 and 3.8.2pip 20.1Kali Linux 2020.1git clone https://github.com/AzizKpln/Moriarty-Projectchmod 755 install.sh ./install.shpip3 install -r requiremenets.txtand I've thisTemat: Re: [AzizKpln/Moriarty-Project] problem (#4)Data: 2020-05-10 12:40Nadawca: "Aziz Kaplan" Adresat: "AzizKpln/Moriarty-Project" ; DW: "shanow7" ; "Author" ; 
Try to install the tool again I made some changes.
I installed and I ran the tool successfully in kali2020.1 it shouldnt give an error.

**Comment by AzizKpln** [comment]
Just like I said please try to install the tool again I made some changes in installation file.It seems like certifi module is not installed in your system 

> pip3 install certifi 

should fix your issue

**Comment by shanow7** [comment]
I installed the tool again and certifi  Temat: Re: [AzizKpln/Moriarty-Project] problem (#4)Data: 2020-05-10 18:25Nadawca: "Aziz Kaplan" Adresat: "AzizKpln/Moriarty-Project" ; DW: "shanow7" ; "Author" ; 
Just like I said please try to install the tool again I made some changes in installation file.It seems like certifi module is not installed in your system

pip3 install certifi

should fix your issue

**Comment by AzizKpln** [comment]
I don't understand you can you write more clearly?

**Comment by shanow7** [comment]
I installed the tool again, I also installed pip3 install certifi and nothing changed, in the attachment I sent a screenshot of the problem with running Temat: Re: [AzizKpln/Moriarty-Project] problem (#4)Data: 2020-05-10 19:07Nadawca: "Aziz Kaplan" Adresat: "AzizKpln/Moriarty-Project" ; DW: "shanow7" ; "Author" ; 
I don't understand you can you write more clearly?

**Comment by AzizKpln** [comment]
I removed the requests module from the tool you can try to install it again it looks like error is because of requests module

**Comment by shanow7** [comment]
thx is ok :) Temat: Re: [AzizKpln/Moriarty-Project] problem (#4)Data: 2020-05-10 19:30Nadawca: "Aziz Kaplan" Adresat: "AzizKpln/Moriarty-Project" ; DW: "shanow7" ; "Author" ; 
I removed the requests module from the tool you can try to install it again it looks like error is because of requests module

**Comment by AzizKpln** [comment]
it is solved

**Comment by shanow7** [comment]
hi,the program has been successfully installed but does not return results, screenshot is attached Temat: Re: [AzizKpln/Moriarty-Project] problem (#4)Data: 2020-05-10 12:40Nadawca: "Aziz Kaplan" Adresat: "AzizKpln/Moriarty-Project" ; DW: "shanow7" ; "Author" ; 
Try to install the tool again I made some changes.
I installed and I ran the tool successfully in kali2020.1 it shouldnt give an error.
