### ISSUE TITLE
Owner Name/Number Information:  Traceback (most recent call last):

### ISSUE THREAD

**Issue by mrlink-white** [AzizKpln/Moriarty-Project#42]
when i run the tool : 
python3 Moriarty.py -n +201xxxxxxxx

it gives me this error :
Owner Name/Number Information:

Traceback (most recent call last):
  File "/home/mrlink/Downloads/Moriarty-Project/Moriarty.py", line 166, in <module>
    microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
  File "/home/mrlink/Downloads/Moriarty-Project/Moriarty.py", line 61, in microsoft_mail
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.NAME, "loginfmt"))).send_keys(username)
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webelement.py", line 540, in send_keys
    {'text': "".join(keys_to_typing(value)),
  File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/utils.py", line 146, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()

**Comment by traderpedroso** [comment]
> when i run the tool : 
> 
> python3 Moriarty.py -n +201xxxxxxxx
> 
> 
> 
> it gives me this error :
> 
> Owner Name/Number Information:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "/home/mrlink/Downloads/Moriarty-Project/Moriarty.py", line 166, in <module>
> 
>     microsoft_mail(options.phone_number,options.microsoft_mail_address,options.mail_password)
> 
>   File "/home/mrlink/Downloads/Moriarty-Project/Moriarty.py", line 61, in microsoft_mail
> 
>     WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.NAME, "loginfmt"))).send_keys(username)
> 
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/remote/webelement.py", line 540, in send_keys
> 
>     {'text': "".join(keys_to_typing(value)),
> 
>   File "/usr/local/lib/python3.9/dist-packages/selenium/webdriver/common/utils.py", line 146, in keys_to_typing
> 
>     for i in range(len(val)):
> 
> TypeError: object of type 'NoneType' has no len()

Use Python3.7

**Comment by AzizKpln** [comment]
Updated
