### ISSUE TITLE
Unknown Issue Completing Scan

### ISSUE THREAD

**Issue by lpoels** [AzizKpln/Moriarty-Project#45]
Hey Guys. 
When i Installed the project and had a few driver issues that I had to work out; but i got that sorted and now it launches fine. I can enter my login info, login works (verified by microsoft activity), and the scan begins. 
I get the correct results for country, timezone and i amagine carrier (if available); but then it errors out. Screen shots attached.
![Screen Shot 2022-03-10 at 7 59 18 PM](https://user-images.githubusercontent.com/75100747/157781860-83caae7e-5703-400d-aa2b-f6b244ac27cb.png)

Ive tried re-installing chrome drivers and the program itself a few times, no luck.
As suggested, i also tried this as normal user and sudo; no changes...
Any advice, am i missing something?

**Comment by augustinewafula** [comment]
> Hey Guys. When i Installed the project and had a few driver issues that I had to work out; but i got that sorted and now it launches fine. I can enter my login info, login works (verified by microsoft activity), and the scan begins. I get the correct results for country, timezone and i amagine carrier (if available); but then it errors out. Screen shots attached. ![Screen Shot 2022-03-10 at 7 59 18 PM](https://user-images.githubusercontent.com/75100747/157781860-83caae7e-5703-400d-aa2b-f6b244ac27cb.png)
> 
> Ive tried re-installing chrome drivers and the program itself a few times, no luck. As suggested, i also tried this as normal user and sudo; no changes... Any advice, am i missing something?

i'm facing the same issue

**Comment by lpoels** [comment]
SOLVED:
Stupid Issue. Turns out my Linux machine was still pointed at my PiHole DNS server and requests were being blocked. Changed to static DNS servers (cloud-flare) and the script can continue.  This actually fixes quite a few random bugs i'd been having *Facepalm*

New Problem:
Still can't get the web-drivers working.... I've installed chromedriver and chromedriver_py multiple times with no changes; Thought maybe because i was running in a headless SSH session; tried VNC, no changes.

Any Advice would be appreciated!
Thanks

**Comment by TigerMan1159** [comment]
> SOLVED: Stupid Issue. Turns out my Linux machine was still pointed at my PiHole DNS server and requests were being blocked. Changed to static DNS servers (cloud-flare) and the script can continue. This actually fixes quite a few random bugs i'd been having _Facepalm_
> 
> New Problem: Still can't get the web-drivers working.... I've installed chromedriver and chromedriver_py multiple times with no changes; Thought maybe because i was running in a headless SSH session; tried VNC, no changes.
> 
> Any Advice would be appreciated! Thanks

How to change my Kali linux DNS server to cloud-flare?

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
