### ISSUE TITLE
Important note: this tool will alert the phone number owner

### ISSUE THREAD

**Issue by danielleschn** [AzizKpln/Moriarty-Project#46]
Ran the tool on two phone numbers I have and received a 2FA text from (833) 640-1079. Unsure exactly what service that is associated with, but I wanted to let people know that this tool will send people a text if you run it on their phone number.

**Comment by TigerMan1159** [comment]
really? i've tried it to my phone number but i didn't get alert or anything.

and i got some error like [https://github.com/AzizKpln/Moriarty-Project/issues/45](url)

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
