### ISSUE TITLE
install doesn't right work

### ISSUE THREAD

**Issue by re-24-pl** [AzizKpln/Moriarty-Project#47]
a first information: i have macos as operating system.

after the install I get the following message:

```
sudo: apt-get: command not found
sudo: apt-get: command not found
unzip: cannot find or open chromedriver_linux64.zip, chromedriver_linux64.zip.zip or chromedriver_linux64.zip.ZIP.
rm: chromedriver_linux64.zip: No such file or directory
cp: directory path does not exist
cp: directory risks_and_deep_search does not exist
cp: directory social_media does not exist
sudo: apt-get: command not found
```
.
.

```
chown: **: No such file or directory
chown: **:**: No such file or directory
chown: **: No such file or directory
chown: **: No such file or directory
```

Chromedriver etc is actually installed. but I don't understand why "cp:..." are not found. They are included in this Moriarty download folder.

after usage; I get only the general information about the number - Country, time zone, provider -

Where is the problem?

**Comment by lamriy** [comment]
you re not on a debian based linux distribution right?

**Comment by re-24-pl** [comment]
No, I'm not. I use a macOS as the operating system.

Gesendet mittels einer sicheren E-Mail von [ProtonMail](https://protonmail.com/).

------- Original Message -------
lamriy ***@***.***> schrieb am Sonntag, 17. April 2022 um 02:45:

**Comment by ErhoSen** [comment]
It would be cool if someone pack the script into Docker image, so it will be easy to run

**Comment by lamriy** [comment]
The install script is made for debian type distributions

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
