### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by imakealol** [AzizKpln/Moriarty-Project#48]
Hello when I run python3 Moriarty.py -rf -pn +49xxxxx on Ubuntu 20 , I get the following error.

Traceback (most recent call last):
  File "/home/projekt/Moriarty-Project/DeepInfo/risks.py", line 31, in spamcallsStart
    user_reports=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/p[1]"))).text
  File "/home/projekt/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5642b2ca1ad3 <unknown>
#1 0x5642b2a01568 <unknown>
#2 0x5642b2a37c46 <unknown>
#3 0x5642b2a37e01 <unknown>
#4 0x5642b2a6aa64 <unknown>
#5 0x5642b2a5561d <unknown>
#6 0x5642b2a68824 <unknown>
#7 0x5642b2a554e3 <unknown>
#8 0x5642b2a2ad1a <unknown>
#9 0x5642b2a2be75 <unknown>
#10 0x5642b2ccfefd <unknown>
#11 0x5642b2ce919b <unknown>
#12 0x5642b2cd1c65 <unknown>
#13 0x5642b2ce9ec8 <unknown>
#14 0x5642b2cc5360 <unknown>
#15 0x5642b2d05a68 <unknown>
#16 0x5642b2d05be8 <unknown>
#17 0x5642b2d1f7fd <unknown>
#18 0x7f185ccc3d80 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projekt/Moriarty-Project/DeepInfo/risks.py", line 45, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/span[2]"))).text
  File "/home/projekt/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5642b2ca1ad3 <unknown>
#1 0x5642b2a01568 <unknown>
#2 0x5642b2a37c46 <unknown>
#3 0x5642b2a37e01 <unknown>
#4 0x5642b2a6aa64 <unknown>
#5 0x5642b2a5561d <unknown>
#6 0x5642b2a68824 <unknown>
#7 0x5642b2a554e3 <unknown>
#8 0x5642b2a2ad1a <unknown>
#9 0x5642b2a2be75 <unknown>
#10 0x5642b2ccfefd <unknown>
#11 0x5642b2ce919b <unknown>
#12 0x5642b2cd1c65 <unknown>
#13 0x5642b2ce9ec8 <unknown>
#14 0x5642b2cc5360 <unknown>
#15 0x5642b2d05a68 <unknown>
#16 0x5642b2d05be8 <unknown>
#17 0x5642b2d1f7fd <unknown>
#18 0x7f185ccc3d80 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/projekt/Moriarty-Project/Moriarty.py", line 175, in <module>
    MP.run()
  File "/home/projekt/Moriarty-Project/Moriarty.py", line 145, in run
    self.spamcalls_()
  File "/home/projekt/Moriarty-Project/Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "/home/projekt/Moriarty-Project/DeepInfo/risks.py", line 57, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/h4"))).text
  File "/home/projekt/.local/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5642b2ca1ad3 <unknown>
#1 0x5642b2a01568 <unknown>
#2 0x5642b2a37c46 <unknown>
#3 0x5642b2a37e01 <unknown>
#4 0x5642b2a6aa64 <unknown>
#5 0x5642b2a5561d <unknown>
#6 0x5642b2a68824 <unknown>
#7 0x5642b2a554e3 <unknown>
#8 0x5642b2a2ad1a <unknown>
#9 0x5642b2a2be75 <unknown>
#10 0x5642b2ccfefd <unknown>
#11 0x5642b2ce919b <unknown>
#12 0x5642b2cd1c65 <unknown>
#13 0x5642b2ce9ec8 <unknown>
#14 0x5642b2cc5360 <unknown>
#15 0x5642b2d05a68 <unknown>
#16 0x5642b2d05be8 <unknown>
#17 0x5642b2d1f7fd <unknown>
#18 0x7f185ccc3d80 <unknown>

**Comment by PawnStorm0x** [comment]
i have the same problem i tested many thing but nothing work

**Comment by juliarjan** [comment]
same here i got that error too..

**Comment by Belicuss** [comment]
Same problem here. No idea how to solve it

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
