### ISSUE TITLE
error installing tool 

### ISSUE THREAD

**Issue by sirhof** [AzizKpln/Moriarty-Project#56]
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.7.0,>=0.6.0
  Downloading s3transfer-0.6.0-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.6/79.6 kB 2.5 MB/s eta 0:00:00
Collecting botocore<1.28.0,>=1.27.46
  Downloading botocore-1.27.46-py3-none-any.whl (9.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.0/9.0 MB 4.3 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/lib/python3/dist-packages (from botocore<1.28.0,>=1.27.46->boto3) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/lib/python3/dist-packages (from botocore<1.28.0,>=1.27.46->boto3) (1.26.9)
Installing collected packages: jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.24.46 botocore-1.27.46 jmespath-1.0.1 s3transfer-0.6.0
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not open requirements file: [Errno 2] No existe el fichero o el directorio: 'requirements.txt'

**Comment by sirhof** [comment]
ant the file exist..

                                                                                                                                                                                                                                            
┌──(sirhof2㉿Sirhof2)-[~/Moriarty-Project]
└─$ ls                  
banners  DeepInfo  __help__.py  images  install.sh  LICENSE  location  Moriarty  Moriarty.py  OutlookAccount  README.md  requirements.txt  r_Scripts  socialMedia

**Comment by AzizKpln** [comment]
Hi, the project is updated. You can use it without receiving errors now. 

Tested OS: Parrot Linux, Kali Linux
