### ISSUE TITLE
The code is showing some timeout errors

### ISSUE THREAD

**Issue by harshajl04** [AzizKpln/Moriarty-Project#57]
![image](https://user-images.githubusercontent.com/64984407/184163265-aac16183-8d01-448f-8e09-0371ce01c238.png)
![image](https://user-images.githubusercontent.com/64984407/184163354-f24e5f29-4bd4-478d-a945-473adb20f56b.png)

**Comment by AzizKpln** [comment]
Hello, this project needs an update. I'm currently working on it. I'm moving this project to playwright and website based usage.
