### ISSUE TITLE
Infinite loading

### ISSUE THREAD

**Issue by gamesprogramist** [AzizKpln/Moriarty-Project#58]
I put a search for a Russian number (+7927). Half an hour has passed and 0 results.
![image](https://user-images.githubusercontent.com/57540446/186727163-5e83838c-f752-4f4a-9420-1ff4de28a7b0.png)

**Comment by AzizKpln** [comment]
Hi,
i just tested the features you've selected. Everything works fine. I'll write you possible problems and solutions:

1- You might didn't give a correct gmail account. You can generate a fresh account.
2- Your system requirements might be low. This might cause playwright not to work properly. Try to give at least 4 GB of ram. If you're using Virtualbox, try to insert guest additions CD image
3- Your OS might be too old. Try to use the newest Kali or Parrot Linux.
4- Playwright may not have installed properly. Try to install playwright manually. Give these commands:
```
apt update && apt upgrade -y
apt install python3-pip -y
python3 -m pip install playwright
python3 -m playwright install
python3 -m playwright install chromium
python3 -m playwright install firefox
```

Let me know if it's fixed.
