### ISSUE TITLE
INSTALLING ERROR

### ISSUE THREAD

**Issue by pretech86** [AzizKpln/Moriarty-Project#6]
root@kali:~/tools/recconessance/Moriarty-Project# pip3 install -r requiremenets.txt

Traceback (most recent call last):

  File "/usr/bin/pip3", line 6, in <module>

    from pkg_resources import load_entry_point

  File "/usr/local/lib/python3.8/dist-packages/pkg_resources.py", line 1479, in <module>

    register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)

AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'

**Comment by mateusfg7** [comment]
you wrote requiremen**e**ts.txt, take off the **e** in the end.
if not work, try with `python3 -m pip install -r requirements.txt`

**Comment by AzizKpln** [comment]
issue has been fixed you dont have to input pip3 install -r requirements.txt anymore
