### ISSUE TITLE
cant work

### ISSUE THREAD

**Issue by sirhof** [AzizKpln/Moriarty-Project#60]
Note: The tool won't work properly if you didn't give correct email information
GENERAL INFORMATION ABOUT NUMBER
[+]Country:Spain
[+]Time Zone:Atlantic/Canary
[+]Carrier:Vodafone
Traceback (most recent call last):
  File "/home/sirhof2/Moriarty-Project/DeepInfo/risks.py", line 31, in spamcallsStart
    user_reports=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/p[1]"))).text
  File "/home/sirhof2/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560ba5da3cd3 <unknown>
#1 0x560ba5bab968 <unknown>
#2 0x560ba5be2fd7 <unknown>
#3 0x560ba5be31a1 <unknown>
#4 0x560ba5c16154 <unknown>
#5 0x560ba5c00bdd <unknown>
#6 0x560ba5c13ea8 <unknown>
#7 0x560ba5c00aa3 <unknown>
#8 0x560ba5bd63fa <unknown>
#9 0x560ba5bd7555 <unknown>
#10 0x560ba5deb2bd <unknown>
#11 0x560ba5def418 <unknown>
#12 0x560ba5dd536e <unknown>
#13 0x560ba5df0078 <unknown>
#14 0x560ba5dc9bb0 <unknown>
#15 0x560ba5e0cd58 <unknown>
#16 0x560ba5e0ced8 <unknown>
#17 0x560ba5e26cfd <unknown>
#18 0x7f5e63f6cd80 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sirhof2/Moriarty-Project/DeepInfo/risks.py", line 45, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/span[2]"))).text 
  File "/home/sirhof2/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560ba5da3cd3 <unknown>
#1 0x560ba5bab968 <unknown>
#2 0x560ba5be2fd7 <unknown>
#3 0x560ba5be31a1 <unknown>
#4 0x560ba5c16154 <unknown>
#5 0x560ba5c00bdd <unknown>
#6 0x560ba5c13ea8 <unknown>
#7 0x560ba5c00aa3 <unknown>
#8 0x560ba5bd63fa <unknown>
#9 0x560ba5bd7555 <unknown>
#10 0x560ba5deb2bd <unknown>
#11 0x560ba5def418 <unknown>
#12 0x560ba5dd536e <unknown>
#13 0x560ba5df0078 <unknown>
#14 0x560ba5dc9bb0 <unknown>
#15 0x560ba5e0cd58 <unknown>
#16 0x560ba5e0ced8 <unknown>
#17 0x560ba5e26cfd <unknown>
#18 0x7f5e63f6cd80 <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sirhof2/Moriarty-Project/Moriarty.py", line 175, in <module>
    MP.run()
  File "/home/sirhof2/Moriarty-Project/Moriarty.py", line 145, in run
    self.spamcalls_()
  File "/home/sirhof2/Moriarty-Project/Moriarty.py", line 122, in spamcalls_
    spamcalls().spamcallsStart(self.phoneNumber)
  File "/home/sirhof2/Moriarty-Project/DeepInfo/risks.py", line 57, in spamcallsStart
    spam_risk=WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.XPATH, "/html/body/div[2]/div[1]/div/div[2]/div[1]/div/div[1]/h4"))).text
  File "/home/sirhof2/.local/lib/python3.10/site-packages/selenium/webdriver/support/wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x560ba5da3cd3 <unknown>
#1 0x560ba5bab968 <unknown>
#2 0x560ba5be2fd7 <unknown>
#3 0x560ba5be31a1 <unknown>
#4 0x560ba5c16154 <unknown>
#5 0x560ba5c00bdd <unknown>
#6 0x560ba5c13ea8 <unknown>
#7 0x560ba5c00aa3 <unknown>
#8 0x560ba5bd63fa <unknown>
#9 0x560ba5bd7555 <unknown>
#10 0x560ba5deb2bd <unknown>
#11 0x560ba5def418 <unknown>
#12 0x560ba5dd536e <unknown>
#13 0x560ba5df0078 <unknown>
#14 0x560ba5dc9bb0 <unknown>
#15 0x560ba5e0cd58 <unknown>
#16 0x560ba5e0ced8 <unknown>
#17 0x560ba5e26cfd <unknown>
#18 0x7f5e63f6cd80 <unknown>

**Comment by AzizKpln** [comment]
Hello, this is not the correct version. This tool has been updated. Please use the latest version
