### ISSUE TITLE
infinite loading even when you select for only SocialMedia search

### ISSUE THREAD

**Issue by cybermagnetar** [AzizKpln/Moriarty-Project#61]
hello devs. The idea and the script is no doubt brilliant but i dont get it if its the script thats not optimised because my device is decent enough. 
even when you want to search for one feature it is going through every one of them and causing infinite loading time.
i would suggest if you add a sub feature for one oparticular feature search and in that too sub-scrapping like:
SOCIALMEDIA->INSTAGRAM.

maybe low to mid end devices might get faster results.
been runnin for more than 55 minutes + man. It shouldnt be taking this long!? Right?

please look into the matter asap. again loved the script. great work. 

![moriarty](https://user-images.githubusercontent.com/73709155/189469887-5748e36b-b117-4ced-9c56-400f79cf281d.png)

**Comment by AzizKpln** [comment]
Hi,
Looks like playwright did not install properly. Can you check if the library is installed? You can simply type:
```
python3
import playwright
```

**Comment by Reginmand** [comment]
Перезагрузка страницы и нет сканирования, а только находит номер телефона (а именно страна и оператор мобильной связи и больше нечего)

[*] Feature On Progress - SpamRisk Algorithm1

[-] No spam risk information found for this number. | SpamRisk Algorithm2

[*]FindOwner Algorithm 1 |Feature is on progress. Please wait.

[*]FindOwner Algorithm 2 |Feature is on progress. Please wait.



[*]SocialMedia - Facebook |Feature is on progress. Please wait.

[*]SocialMedia - Instagram |Feature is on progress. Please wait.

[*]SocialMedia - Twitter |Feature is on progress. Please wait.

[*]SocialMedia - Google |Feature is on progress. Please wait.

[*]SocialMedia - Microsoft | Feature is on progress. Please wait.

[*]GetComments Algorithm 1| Feature is on progress. Please wait.

[*]GetComments Algorithm 2| Feature is on progress. Please wait.

**Comment by ghost** [comment]
it still doesnt work for me, another way to fix it?
