### ISSUE TITLE
social media

### ISSUE THREAD

**Issue by varavatos** [AzizKpln/Moriarty-Project#64]
does not show social accounts related to the number

**Comment by AzizKpln** [comment]
This tool doesn't provide the feature you're telling. It shows if the phone number is connected to a social media account.

**Comment by varavatos** [comment]
the number i tried is already connected to the fb and instagram but it doesnt show any result. waited for 4hrs.

**Comment by ManuelBot59** [comment]
the same thing happens to me too, that's what I was referring to when I commented on linkedin, that it's not showing results in relation to social networks

**Comment by ManuelBot59** [comment]
@AzizKpln the same thing happens to me too, that's what I was referring to when I commented on linkedin, that it's not showing results in relation to social networks

**Comment by AzizKpln** [comment]
#58

**Comment by Andrejki** [comment]
Has anyone solved it by  @AzizKpln instructions in #58 ?
I have not. It just showed me that it is not a spam number, that is is not connected to Microsoft account. But regarding the owner and social media rest - nothing. And it was running for more than 4 hours.
