### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by Thalmalynx** [AzizKpln/Moriarty-Project#65]
Hello,

I am not a command console pro, far from it. I followed the instructions on the GIT BASH (Windows) and I get the following result : 

Project is currently running. If your browser not showing up,
hostname: unknown option -- I
Try 'hostname --help' for more information.
Please go to this link: http://:8080
Press CTRL+C to kill the webserver.

I tried to go to localhost 8080, but it does not open. ERR_CONNECTION_REFUSED

Can we make the requests from the Command Prompt ?

**Comment by AzizKpln** [comment]
Hi, What's your OS? This project is tested only on debian and ubuntu based operating systems

**Comment by Thalmalynx** [comment]
Aa ok, it's Windows 10, That was simply the problem.
