### ISSUE TITLE
support to use in google cloud shell platform

### ISSUE THREAD

**Issue by ManuelBot59** [AzizKpln/Moriarty-Project#67]
473 / 5.000
Resultados de traducción
I would like to run your tool in the Cloud Shell Editor, is there any way I can adapt it? that the Cloud shell Editor is different. Example of a simple project in the web environment of the Cloud Shell Editor:

cd `mktemp -d` \
     && echo '<html><body>Hello World</body></html>' >./index.html \
     && python -m http.server 8080

**Comment by AzizKpln** [comment]
Solved
