### ISSUE TITLE
Feature Request: Allow root for users of Kali Linux

### ISSUE THREAD

**Issue by anoduck** [AzizKpln/Moriarty-Project#68]
Because of what this app does, there is a higher than normal probability the user will be running Kali Linux, and as we all know, Kali's default user account is root. Since they might not want to create a separate user account just for this script, a good resolution would be the creation of a system account solely to run this script as. 

It would be nice if this resolution were included in the installation script, or if Kali users could disable the non-root user requirement.

**Comment by AzizKpln** [comment]
Hi,
The default user of kali linux is not root. When you setup kali linux it generates a normal user for you and that user is in the Group of root. What you're telling is not secure. It happens to be in old versions of kali linux but currently, kali doesn't provide what you are telling.

I will update this tool after 1 month. I might add root feature as well

**Comment by anoduck** [comment]
@AzizKpln If Kali changed, it was most assuredly was after the installation of Kali on my system, and recently. Since Kali releases are rolling, there are few chances for established users to have known about this, or benefit from it. It was not too long ago I referred to this on a Kali forum, and no mention of it was made.

I am not a member of Kali's development group, so I have no authority or input on design or implementation of security policy. Of course, it is insecure, It has always been insecure. It was this way, since it was originally released from a fork of Ubuntu as Backtrack. 

Do we really need every version of playwright? I really should have gone with a Docker image for this.
