### ISSUE TITLE
Execution Error

### ISSUE THREAD

**Issue by mateusfg7** [AzizKpln/Moriarty-Project#7]
I have an error when execute the script, after check twitter account:
```
Traceback (most recent call last):
  File "Moriarty.py", line 196, in <module>
    google_phone(options.phone_number)
  File "Moriarty.py", line 134, in google_phone
    google.gg(phone_number)
  File "/home/mateusfg7/Tools/Moriarty-Project/social_media/google.py", line 36, in gg
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '/html/body/div[1]/div[1]/footer/div/div/div[1]/div[1]/div[38]'))).click()
  File "/usr/lib/python3/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 


```

![image](https://user-images.githubusercontent.com/40613276/82047299-f77b6800-9688-11ea-8560-703a3d26a3de.png)

**Comment by AzizKpln** [comment]
I Will check the bugs but I got final exams bro I Will release the v2. 3 after May.
But try to use the tool again it Could be solved thanks for using moriarty I appreciated

**Comment by shanow7** [comment]
Hi, I've this
/Moriarty-Project$ python3 Moriarty.py -h
Traceback (most recent call last):
  File "Moriarty.py", line 15, in <module>
    from clint.textui import colored
ModuleNotFoundError: No module named 'clint'

**Comment by AzizKpln** [comment]
you have to issue this command: "pip install -r requirements.txt"
But I suggest you guys to wait because Moriarty project will be something more than now it is.

**Comment by shanow7** [comment]
I used this command but nothing was change
ok, I'll wait...

**Comment by AzizKpln** [comment]
issue has been fixed
