### ISSUE TITLE
Kontrol Gerekli.

### ISSUE THREAD

**Issue by ahmetinanckoca** [AzizKpln/Moriarty-Project#8]
python3 Moriarty.py -g mail@gmail.com -p 1234 -n +90555555555 sorgusunda

```
Traceback (most recent call last):
  File "Moriarty.py", line 229, in <module>
    with open("output/comments1.txt","w+") as file:
PermissionError: [Errno 13] Permission denied: 'output/comments1.txt'
```
Hatası dönüyor.

Yönetici izni ile çalıştırıldığında ise; 

```
Traceback (most recent call last):
  File "Moriarty.py", line 14, in <module>
    from clint.textui import colored
ModuleNotFoundError: No module named 'clint'
```

hatası dönüyor.

**Comment by AzizKpln** [comment]
/opt/ dizinine değil desktop a kur ardından install.sh dosyasını çalıştır

**Comment by AzizKpln** [comment]
Araç root olmadan çalıştırılmak zorundadır. Ve root yetkisi isteyen bir dizinde çalıştırlamaz

This tool has to be run as non-root. And it has to be downloaded in the directory that doesnt require any root permission(like /opt/ or /root/) that feature will be added in the next release
