### ISSUE TITLE
try to use microsoft account

### ISSUE THREAD

**Issue by pretech86** [AzizKpln/Moriarty-Project#9]
thanks for the tool but it always said try to use microsoft account and sync faild although i used microsoft account

**Comment by AzizKpln** [comment]
You have to input -m parameter for microsoft account. And you have to input your password. There shouldnt be an error as long as you input the information correctly. Sync error is not something important ignore that

**Comment by pretech86** [comment]
I already entered -m and -p and the tool stuck and not complete

**Comment by AzizKpln** [comment]
Are you root? You have run the tool as a  normal user

**Comment by pretech86** [comment]
yes im root 

[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]This Phone Number Is Not Connected To Any Yandex Account!
--------------------------------------------------
Deep Search:
Traceback (most recent call last):
  File "Moriarty.py", line 306, in <module>
    deep_info_three(options.phone_number)
  File "Moriarty.py", line 217, in deep_info_three
    deep_info3.deep_three(phone_number)
  File "/root/tools/reconnesence/Moriarty-Project/risks_and_deep_search/deep_info3.py", line 29, in deep_three
    WebDriverWait(driver, 10).until(EC.element_to_be_clickable((By.XPATH, '//*[@id="oos_content"]/div[1]/form/table/tbody/tr/td[1]/input'))).send_keys(phone_number)
  File "/usr/local/lib/python3.8/dist-packages/selenium/webdriver/support/wait.py", line 86, in until
raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by AzizKpln** [comment]
You have to run it as non-root. Read the readme.md file. I run it and it works properly

**Comment by pretech86** [comment]
i test it on a normal user also it give me the same error

**Comment by AzizKpln** [comment]
Where are you from? I tried it and it didn't issue me an error

**Comment by pretech86** [comment]
saudi arabia

**Comment by StarsAlAndroid** [comment]
im also have this error 

Owner Name/Number Information:                                                                                                                                        
                                                                                                                                                                      
[!]This Will Take A While Please Wait <3                                                                                                                              
[-]Please try to use microsoft mail.                                                                                                                                  
[-]Sync Error.                                                                                                                                                        
[-]Sync Error.

**Comment by AzizKpln** [comment]
Those are not something important. You can ignore them

**Comment by StarsAlAndroid** [comment]
Ok thanks  .

>How i can send sms messages ?

>and how i can get  Amazon Key !!

**Comment by AzizKpln** [comment]
print(colored.yellow("[!]https://www.youtube.com/watch?v=5oBHvl1hurE This Video Will Help You If Don't Know How To Use Aws."))

**Comment by pretech86** [comment]
Accounts For The Number:
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
[-]Something Went Wrong! Please Reset Your Modem And Try To Use The Tool Again!
--------------------------------------------------
Deep Search:
Traceback (most recent call last):
  File "Moriarty.py", line 304, in <module>
    deep_info_one(options.phone_number)
  File "Moriarty.py", line 213, in deep_info_one
    deep_info1.deep_one(phone_number)
  File "/root/tools/reconnesence/Moriarty-Project/risks_and_deep_search/deep_info1.py", line 27, in deep_one
    driver = webdriver.Chrome(options=options,service=serv)
TypeError: __init__() got an unexpected keyword argument 'service'

**Comment by johndoehack** [comment]
i have kali linux i run your program on root and not root user and i get error all the time.

**Comment by AzizKpln** [comment]
v2.4 has been released. Try to install the tool again.

**Comment by shanow7** [comment]
I've this:

Deep Search:

Traceback (most recent call last):
  File "Moriarty.py", line 295, in <module>
    deep_info_one(options.phone_number)
  File "Moriarty.py", line 213, in deep_info_one
    deep_info1.deep_one(phone_number)
  File "/home/csi/Moriarty-Project/risks_and_deep_search/deep_info1.py", line 27, in deep_one
    driver = webdriver.Chrome(options=options,service=serv)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 100, in __init__
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 152, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 249, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 318, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81

**Comment by AzizKpln** [comment]
You have to download lates version of chrome driver. When installation is done, copy the chromedriver into Moriarty-Project/path directory.
